### ISSUE TITLE
Research and Implement Startegy Pattern

### ISSUE THREAD

**Issue by HarryAmmon** [HarryAmmon/Employee-Pay-Test#26]

**Comment by HarryAmmon** [comment]
A service locator class should be created. Use a dictionary where the key is the type of the service that is needed.

## TODO:
- [ ] Create a service locator class
- [ ] Store both Employee Services in this class
- [ ] Inject the service locator class to the BetterCommandServices class
- [ ] Remove the injection of both EmployeeServices

Use [this article](https://www.c-sharpcorner.com/UploadFile/dacca2/service-locator-design-pattern/) for reference.
